name: actions-trial
on: [push]
jobs:
 check-bats-version:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2

    - name: run script
      working-directory: ~/
      run: sh ./GCF-test.sh
